name: snap_serial
version: '0.1'
summary: Serialtest
description: |
  Test serial port  
grade: devel
confinement: devmode

apps:
  offlineimpa:
    command: bin/offlineimap

parts:
  snap_serial:
    plugin: python
    python-version: python2
    source: https://github.com/7ider5/snap_serial.git
    source-tag: 
